import React from "react";
import Head from "next/head";

const About = () => {
  return (
    <div>
      <Head>
        <title>About | Seko House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>About</main>

      <footer></footer>
    </div>
  );
};

export default About;
