import Head from "next/head";
import Image from "next/image";
import HomeAnimation from "../components/HomeAnimation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seko House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home</h1>

        <div className="w-96 h-96">
          <HomeAnimation />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
