import Head from "next/head";
import Image from "next/image";
import HomeAnimation from "../components/HomeAnimation";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seko House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-hidden">
        <motion.div
          initial={{
            opacity: 0,
          }}
          animate={{
            opacity: 1,
            transition: {
              delay: 0.5,
            },
          }}
        >
          <div className="w-full h-[80vh] relative">
            <div className="absolute left-20 top-96 z-10">
              <h2 className="text-6xl mb-8">Let Me Down To Earth</h2>
              <a href="https://open.spotify.com/artist/1uzEmG1cUynJOjJi0LTNvf?si=oAbhsZjlSWyIlyLOLGQEbw&nd=1">
                <span className="text-4xl outline stroke-1 p-4 italic hover:bg-[#ffffff] hover:text-black hover:rounded-2xl transition-all duration-300 ">
                  Listen Now
                </span>
              </a>
            </div>
            <div className="w-[100%] h-[75vh] absolute">
              <HomeAnimation />
            </div>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
