import React from "react";
import { motion } from "framer-motion";
import Head from "next/head";
import Footer from "../components/Footer";
import Image from "next/image";

const Marquee = () => {
  return (
    <div className="relative flex overflow-x-hidden rotate-[35deg] ">
      <div className="py-12 animate-marquee whitespace-nowrap">
        <span className="text-5xl mx-4">COMING SOON</span>
        <span className="text-5xl mx-4">COMING SOON</span>
      </div>

      <div className="absolute top-0 py-12 animate-marquee2 whitespace-nowrap">
        <span className="text-5xl mx-4">COMING SOON</span>
        <span className="text-5xl mx-4">COMING SOON</span>
      </div>
    </div>
  );
};

const KnowornoImage = () => {
  return (
    <a href="https://www.knoworno.com/">
      <div className="relative w-48 h-48">
        <Image
          src="/knoworno.webp"
          alt="knoworno"
          layout="fill"
          objectFit="cover"
        />
      </div>
    </a>
  );
};

const Merch = () => {
  return (
    <motion.div
      initial={{ scale: 0.8, opacity: 0 }}
      animate={{ scale: 1, opacity: 1 }}
    >
      <Head>
        <title>Seko House | Merch </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen flex justify-center items-center relative ">
        <div className="absolute left-[25%] bottom-[25%]">
          <KnowornoImage />
        </div>
        <Marquee />
        <div className="absolute right-[25%] top-[25%]">
          <KnowornoImage />
        </div>
      </main>
    </motion.div>
  );
};

export default Merch;
