import React from "react";
import Head from "next/head";
import ReactPlayer from "react-player";
import { motion } from "framer-motion";

const demos = [
  "https://soundcloud.com/sekohouse/tripwirebysekohouse",
  "https://soundcloud.com/sekohouse/full-circle-ft-salem-prod-seko",
  "https://soundcloud.com/sekohouse/spl-grieve-prod-seko-house",
  "https://soundcloud.com/sekohouse/goyardlost",
  "https://soundcloud.com/sekohouse/fornowmusic-prod-seko",
];

function WeeklyDemos() {
  return (
    <div className="w-full flex flex-col items-center">
      {demos.map((demo) => (
        <div key={demo} className="m-4 bg-yellow-200">
          <ReactPlayer height="100%" url={demo} />
        </div>
      ))}
    </div>
  );
}

const Music = () => {
  return (
    <motion.div
      initial={{ scale: 0.8, opacity: 0 }}
      animate={{ scale: 1, opacity: 1 }}
    >
      <Head>
        <title>Seko House | Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <WeeklyDemos />
      </main>

      <footer></footer>
    </motion.div>
  );
};

export default Music;
