import React from "react";
import Head from "next/head";

const Music = () => {
  return (
    <div>
      <Head>
        <title>Seko House | Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Music</main>

      <footer></footer>
    </div>
  );
};

export default Music;
